name: "Prod Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write   # OIDC ke liye zaruri
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: 3d62d47f-71f5-49b1-aed5-8ce8a45728e4
          tenant-id: 986adbd0-1687-41ed-9818-bd58c967382b
          subscription-id: 239f86cf-d0d2-4954-935f-40e39253100c
        
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/prod
        
      - name: Terraform Init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: environments/prod        
      
      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        working-directory: environments/prod    
        
  terraform-apply:    
    runs-on: self-hosted
    needs: terraform-init-plan
    environment: prod
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: 3d62d47f-71f5-49b1-aed5-8ce8a45728e4
          tenant-id: 986adbd0-1687-41ed-9818-bd58c967382b
          subscription-id: 239f86cf-d0d2-4954-935f-40e39253100c
          
      - name: Terraform Init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: environments/prod  
