name: "new aks deployment infra workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
 id-token: write
 contents: read

jobs:
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 8c546d3e-0eeb-44e0-ab1b-a7d43bc20acf
          tenant-id: af1a1d72-dd79-4bc0-8fc9-b305fe66df83
          subscription-id: 4e7d9bde-4edb-4e22-a2ce-020148cad621
    

   
    
