name: "Prod Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5
    
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL
            
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/prod
        
      - name: Terraform Init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: environments/prod        
      
      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        working-directory: environments/prod    
        
  terraform-apply:    
    runs-on: self-hosted
    needs: terraform-init-plan
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v5
    
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPALL
          
      - name: Terraform Init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: environments/prod         
          
